name: iOSSDKExample
type: application
platform: iOS
sdk: iOS 15.0
defaults:
  ios:
    deploymentTarget: "15.0"

packages:
  LlamaMobileSDK:
    path: "../../llama_mobile-ios-SDK"

targets:
  iOSSDKExample:
    type: application
    platform: iOS
    sources: [iOSSDKExample]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.llama.mobile.iossdkexample
        SWIFT_VERSION: "5.9"
    dependencies:
      - package: LlamaMobileSDK
        product: LlamaMobileSDK
    resources:
      - path: iOSSDKExample/Assets.xcassets
        type: folder
      - path: models
        type: folder
    info:
      path: iOSSDKExample/Info.plist
      mergeable: true
      properties:
        UIApplicationSceneManifest:
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    entitlements:
      path: iOSSDKExample/ios-sample.entitlements
