pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "androidSDKExample"
include ':app'
include ':llama_mobile-android-SDK'
project(':llama_mobile-android-SDK').projectDir = new File('../../llama_mobile-android-SDK')