pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "androidJavaSDKExample"
include ':app'
include ':llama_mobile_java_sdk'

project(':llama_mobile_java_sdk').projectDir = new File(rootProject.projectDir, '../../llama_mobile-android-java-SDK')